/******************************************************************************/
/***          Generated by IBExpert 2012.09.17 26.12.2017 11:56:37          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;

CREATE DATABASE 'LOCALHOST:D:\a3v\Work\FinHelper\FinHelper\DB\InitDB.fdb'
USER 'SYSDBA' PASSWORD '1'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1251 COLLATION WIN1251;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_CARDS_ID;
SET GENERATOR GEN_CARDS_ID TO 0;

CREATE GENERATOR GEN_CATEGORIES_ID;
SET GENERATOR GEN_CATEGORIES_ID TO 0;

CREATE GENERATOR GEN_MOVES_ID;
SET GENERATOR GEN_MOVES_ID TO 0;

CREATE GENERATOR GEN_ORDERS_ID;
SET GENERATOR GEN_ORDERS_ID TO 0;

CREATE GENERATOR GEN_ORDLINES_ID;
SET GENERATOR GEN_ORDLINES_ID TO 0;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CARDS (
    CARDNUMBER  VARCHAR(256),
    NAME        VARCHAR(256) NOT NULL,
    ID          INTEGER NOT NULL
);


CREATE TABLE CATEGORIES (
    NAME  VARCHAR(256) NOT NULL,
    ID    INTEGER NOT NULL
);


CREATE TABLE MOVES (
    DATAMOVE   TIMESTAMP NOT NULL,
    SUMM       FLOAT NOT NULL,
    CARDID     INTEGER NOT NULL,
    ORDLINEID  INTEGER NOT NULL,
    ID         INTEGER NOT NULL
);


CREATE TABLE ORDERS (
    CARDID   INTEGER,
    COMMENT  VARCHAR(256),
    DOCDATE  TIMESTAMP NOT NULL,
    ID       INTEGER NOT NULL
);


CREATE TABLE ORDLINES (
    COMMENT     VARCHAR(256),
    MOVEDATE    TIMESTAMP NOT NULL,
    SUMM        FLOAT NOT NULL,
    CATEGORYID  INTEGER NOT NULL,
    ORDID       INTEGER NOT NULL,
    ID          INTEGER NOT NULL
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CARDS ADD PRIMARY KEY (ID);
ALTER TABLE CATEGORIES ADD PRIMARY KEY (ID);
ALTER TABLE MOVES ADD CONSTRAINT PK_MOVES PRIMARY KEY (ID);
ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY (ID);
ALTER TABLE ORDLINES ADD CONSTRAINT PK_ORDLINES PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE MOVES ADD CONSTRAINT FK_MOVES_1 FOREIGN KEY (ORDLINEID) REFERENCES ORDLINES (ID);
ALTER TABLE MOVES ADD CONSTRAINT FK_MOVES_2 FOREIGN KEY (CARDID) REFERENCES CARDS (ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_1 FOREIGN KEY (CARDID) REFERENCES CARDS (ID);
ALTER TABLE ORDLINES ADD CONSTRAINT FK_ORDLINES_1 FOREIGN KEY (ORDID) REFERENCES ORDERS (ID);
ALTER TABLE ORDLINES ADD CONSTRAINT FK_ORDLINES_2 FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES (ID);
